# Generated by Django 2.1.1 on 2018-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dosya'),
        ),
    ]
