# Generated by Django 2.1.3 on 2018-11-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Kullanıcı Profilleri'},
        ),
    ]
