# Generated by Django 2.1.3 on 2018-11-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OmeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown_text', models.TextField(max_length=3000, null=True, verbose_name='Markdown yazı')),
                ('html_text', models.TextField(max_length=3000, null=True, verbose_name='HTML yazı')),
            ],
            options={
                'verbose_name': 'Gönderiler',
                'verbose_name_plural': 'Gönderi',
            },
        ),
    ]
