# Generated by Django 2.1.3 on 2018-11-26 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdfiles', '0002_auto_20181114_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='omefile',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='omefile',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=True, related_name='kullanıcı', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
