# Generated by Django 2.1.3 on 2018-11-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdfiles', '0004_omefile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omefile',
            name='slug',
        ),
    ]
