# Generated by Django 2.1.3 on 2018-11-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdfiles', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
