# Generated by Django 2.1.3 on 2018-11-27 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdfiles', '0007_auto_20181127_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omefile',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=True, related_name='omefile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
