# Generated by Django 2.1.3 on 2018-11-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdfiles', '0009_auto_20181128_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='omefile',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
