# Generated by Django 2.1.7 on 2019-02-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdfiles', '0010_omefile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omefile',
            name='html_text',
        ),
    ]
